version: 2                                       # 1/2/2.1の何れかを指定。バージョンによって記述の仕方が異なるので注意（現状であれば、2,2.1のどちらかが推奨みたい
jobs:                                            # 必須固定
  build:                                         # Job名/Jobが1つの場合は必ず"build:"
    docker:                                      # ビルド環境(machine/macosなどのVPCを選ぶことも可能だけど、dockerが主流みたい
      - image: circleci/node:10                  # ビルドイメージを指定。firebaseCLIはnode.js ver6.0.0以上推奨であることを確認しつつ、現在のnode.js推奨バージョンである10を指定
    steps:                                       # 実行内容記述開始の合図
      - run:                                     # firebaseCLI入れる前に念のためnpmバージョンチェック
          name: 'npm version check'
          command: npm --version
      - run:                                     # firebaseCLI入れる前に念のためnode.jsのバージョンチェック
          name: 'Node.js version check'          
          command: node --version
      - checkout                                 # GitHubのリポジトリ配下のファイルを丸っとビルド環境に持ってくる
      - run:                                     # firebaseCLIのインストール
          name: 'Install Firebase CLI'
          command: npm install --save-dev firebase-tools
      - run:                                     # firebaseCLIを使ってデプロイ実行
          name: 'Deploy to Hosting'
          command: ./node_modules/.bin/firebase deploy --token="$FIREBASE_TOKEN"
workflows:                                       # 定義したJobを流すフローを指定
  version: 2
  build_and_deploy:                              # 任意のフロー名でOK
    jobs:                                        # 実行Jobを配下に記述
      - build:                                   # 今回は”build"のみなので、これだけ！あまりフローを組む必要性ないですけど、必須みたいです！
          filters:
            branches:
              only: master                       # filtersでmasterブランチへのコミットのみを対象にflowを動かすように指定
